<a href="https://colab.research.google.com/github/sibat119/pytorch-intro/blob/main/linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [9]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [10]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [11]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [22]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w, b)

tensor([[ 1.4825,  0.3620, -0.2856],
        [-1.7643,  0.1172,  0.0777]], requires_grad=True) tensor([-1.2507, -0.8132], requires_grad=True)


In [23]:
def model(x):
  return x @ w.t() + b

In [24]:
preds = model(inputs)
print(preds)

tensor([[ 118.9490, -118.4122],
        [ 147.2397, -146.0762],
        [ 159.6741, -134.0942],
        [ 154.9684, -172.8558],
        [ 115.8063, -105.8578]], grad_fn=<AddBackward0>)


In [25]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [26]:
loss = mse(targets, preds)
learning_rate = 1e-4
print(loss)

tensor(29033.4844, grad_fn=<DivBackward0>)


In [28]:
loss.backward()
print(w)
print(w.grad)

tensor([[ 1.4825,  0.3620, -0.2856],
        [-1.7643,  0.1172,  0.0777]], requires_grad=True)
tensor([[  5721.6284,   4488.8086,   3024.3027],
        [-19279.1387, -20153.4180, -12582.1553]])


In [30]:
with torch.no_grad():
  w -= w.grad * learning_rate
  b -= b.grad * learning_rate
  w.grad.zero_()
  b.grad.zero_()

In [31]:
print(w)
print(b)

tensor([[ 0.3382, -0.5358, -0.8904],
        [ 2.0915,  4.1479,  2.5942]], requires_grad=True)
tensor([-1.2633, -0.7678], requires_grad=True)


In [32]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(186440.4062, grad_fn=<DivBackward0>)


In [34]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * learning_rate
        b -= b.grad * learning_rate
        w.grad.zero_()
        b.grad.zero_()

In [35]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(7.9479, grad_fn=<DivBackward0>)


In [36]:
preds

tensor([[ 57.2834,  70.2291],
        [ 79.6609, 100.2759],
        [124.2895, 133.9812],
        [ 22.7301,  37.2913],
        [ 96.2804, 118.1337]], grad_fn=<AddBackward0>)

In [37]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])